#!/bin/bash
src=`readlink -e $1`
dir=`dirname "$0"`
if [ $# -eq 0 ] ; then
  echo "Please specity the source"
  exit 1
fi
if [ $# -le 1 ] ; then
  destf=runbf
else
  destf=$2
fi
touch $destf
dest=`readlink -e $destf`
cd "$dir"
if [ ! -f $src ] ; then
  echo "Source does not exist"
  exit 1
fi
make run SRC=$src DEST=${dest} >/dev/null
exit $?
